from .model import VoiceFile, Voice


mnk_voices = Voice(
    resource_name='mnk_voice',
    voices=[
        VoiceFile(name="monaka没有摸", file_name="monaka没有摸.mp3", tag="未分类"),
        VoiceFile(name="mnk的腿是真的废了", file_name="mnk的腿是真的废了.mp3", tag="未分类"),
        VoiceFile(name="哎呀我是个废物", file_name="哎呀我是个废物.mp3", tag="未分类"),
        VoiceFile(name="啊那就不好玩了", file_name="啊那就不好玩了.mp3", tag="未分类"),
        VoiceFile(name="这事没完", file_name="这事没完.mp3", tag="未分类"),
        VoiceFile(name="还剩一点点，快，快打他", file_name="还剩一点点，快，快打他.mp3", tag="未分类"),
        VoiceFile(name="DJ，换歌", file_name="DJ，换歌.mp3", tag="未分类"),
        VoiceFile(name="他喵的燃起来", file_name="他喵的燃起来.mp3", tag="未分类"),
        VoiceFile(name="他喵的燃起来哦快走快走", file_name="他喵的燃起来哦快走快走.mp3", tag="未分类"),
        VoiceFile(name="这也太怪了吧", file_name="这也太怪了吧.mp3", tag="未分类"),
        VoiceFile(name="mnk没用的家伙", file_name="mnk没用的家伙.mp3", tag="未分类"),
        VoiceFile(name="嗯——怪怪的，我觉得怪怪的", file_name="嗯——怪怪的，我觉得怪怪的.mp3", tag="未分类"),
        VoiceFile(name="什么玩意，大白天的干嘛呢", file_name="什么玩意，大白天的干嘛呢.mp3", tag="未分类"),
        VoiceFile(name="我不行，我不能辱薯，我是孝子", file_name="我不行，我不能辱薯，我是孝子.mp3", tag="未分类"),
        VoiceFile(name="mnknb", file_name="mnknb.mp3", tag="未分类"),
        VoiceFile(name="蛋白质女王mnk", file_name="蛋白质女王mnk.mp3", tag="未分类"),
        VoiceFile(name="mnk!寂しい！", file_name="mnk!寂しい！.mp3", tag="未分类"),
        VoiceFile(name="你搁这搁这呢？", file_name="你搁这搁这呢？.mp3", tag="未分类"),
        VoiceFile(name="对涩图没兴趣", file_name="对涩图没兴趣.mp3", tag="未分类"),
        VoiceFile(name="火箭队出场台词薯条mnk版", file_name="火箭队出场台词薯条mnk版.mp3", tag="未分类"),
        VoiceFile(name="烦死了，全是片假名", file_name="烦死了，全是片假名.mp3", tag="未分类"),
        VoiceFile(name="啊！！我怎么把游戏弄没了", file_name="啊！！我怎么把游戏弄没了.mp3", tag="未分类"),
        VoiceFile(name="mnk怕黄爪，懂的都懂！", file_name="mnk怕黄爪，懂的都懂！.mp3", tag="未分类"),
        VoiceFile(name="你要看？不给看！", file_name="你要看？不给看！.mp3", tag="未分类"),
        VoiceFile(name="你怕狗？薯条也怕狗", file_name="你怕狗？薯条也怕狗.mp3", tag="未分类"),
        VoiceFile(name="こんにちは", file_name="こんにちは.mp3", tag="问候"),
        VoiceFile(name="下午花", file_name="下午花.mp3", tag="问候"),
        VoiceFile(name="下午花~", file_name="下午花~.mp3", tag="问候"),
        VoiceFile(name="下午花下午花（阴间）", file_name="下午花下午花（阴间）.mp3", tag="问候"),
        VoiceFile(name="拜拜拜拜", file_name="拜拜拜拜.mp3", tag="问候"),
        VoiceFile(name="祝大家牛年大吉吧", file_name="祝大家牛年大吉吧.mp3", tag="问候"),
        VoiceFile(name="干杯~", file_name="干杯~.mp3", tag="问候"),
        VoiceFile(name="（奥数感）你们早点睡啊，晚安", file_name="（奥数感）你们早点睡啊，晚安.mp3", tag="问候"),
        VoiceFile(name="有事早起上奏，无事卷帘退朝", file_name="有事早起上奏，无事卷帘退朝.mp3", tag="问候"),
        VoiceFile(name="(奥数感)其实我要去吃独食啦", file_name="(奥数感)其实我要去吃独食啦.mp3", tag="问候"),
        VoiceFile(name="尼玛死了", file_name="尼玛死了.mp3", tag="问候"),
        VoiceFile(name="钉宫三连", file_name="钉宫三连.mp3", tag="可爱"),
        VoiceFile(name="笨蛋欧尼酱rua", file_name="笨蛋欧尼酱rua.mp3", tag="可爱"),
        VoiceFile(name="喵喵喵，喵喵喵", file_name="喵喵喵，喵喵喵.mp3", tag="可爱"),
        VoiceFile(name="那个叔叔在和纸片人合影！", file_name="那个叔叔在和纸片人合影！.mp3", tag="可爱"),
        VoiceFile(name="老公老公老公", file_name="老公老公老公.mp3", tag="可爱"),
        VoiceFile(name="老婆老婆老婆", file_name="老婆老婆老婆.mp3", tag="可爱"),
        VoiceFile(name="你向猫猫又近了一步", file_name="你向猫猫又近了一步.mp3", tag="可爱"),
        VoiceFile(name="（拍肚子）哎哟，吃太饱", file_name="（拍肚子）哎哟，吃太饱.mp3", tag="可爱"),
        VoiceFile(name="喵~喵~", file_name="喵~喵~.mp3", tag="可爱"),
        VoiceFile(name="肥肠抱歉，本视频无法播放", file_name="肥肠抱歉，本视频无法播放.mp3", tag="可爱"),
        VoiceFile(name="这个世界不能对我温柔一点吗？", file_name="这个世界不能对我温柔一点吗？.mp3", tag="可爱"),
        VoiceFile(name="我这张脸你还不忍心下手？", file_name="我这张脸你还不忍心下手？.mp3", tag="可爱"),
        VoiceFile(name="你报我身份证得了！", file_name="你报我身份证得了！.mp3", tag="可爱"),
        VoiceFile(name="好甜，像你一样", file_name="好甜像你一样.mp3", tag="可爱"),
        VoiceFile(name="都不理mnk了", file_name="都不理mnk了.mp3", tag="委屈"),
        VoiceFile(name="不能讲不能讲不能讲", file_name="不能讲不能讲不能讲.mp3", tag="委屈"),
        VoiceFile(name="不要不要，不不再也不敢了，不敢了", file_name="不要不要，不不再也不敢了，不敢了.mp3", tag="委屈"),
        VoiceFile(name="不要不要，不讲了，再也不敢了，不敢了", file_name="不要不要，不讲了，再也不敢了，不敢了.mp3", tag="委屈"),
        VoiceFile(name="我好想闻闻言子身上的味道", file_name="我好想闻闻言子身上的味道.mp3", tag="怪话"),
        VoiceFile(name="欣赏翘臀", file_name="欣赏翘臀.mp3", tag="怪话"),
        VoiceFile(name="mnk想被塔打", file_name="mnk想被塔打.mp3", tag="怪话"),
        VoiceFile(name="mnk打你，你别打mnk", file_name="mnk打你，你别打mnk.mp3", tag="怪话"),
        VoiceFile(name="健身环去你mua的_01", file_name="健身环去你mua的_01.mp3", tag="怪话"),
        VoiceFile(name="健身环去你mua的_02", file_name="健身环去你mua的_02.mp3", tag="怪话"),
        VoiceFile(name="哪来的狗，qnmd", file_name="哪来的狗，qnmd.mp3", tag="怪话"),
        VoiceFile(name="你能教我骂人吗？", file_name="你能教我骂人吗？.mp3", tag="怪话"),
        VoiceFile(name="电他牛子！", file_name="电他牛子！.mp3", tag="怪话"),
        VoiceFile(name="服务员！这里有变态啊！！！救命啊！！！", file_name="服务员！这里有变态啊！！！救命啊！！！.mp3", tag="怪话"),
        VoiceFile(name="薯条屁股手感可好了", file_name="薯条屁股手感可好了.mp3", tag="怪话"),
        VoiceFile(name="差点读成铁娘nai头", file_name="差点读成铁娘nai头.mp3", tag="怪话"),
        VoiceFile(name="你们不要当太监啊", file_name="你们不要当太监啊.mp3", tag="怪话"),
        VoiceFile(name="哼哼哼啊啊啊啊啊啊", file_name="目力mnk.mp3", tag="怪话"),
        VoiceFile(name="你是一个一个一个", file_name="你是一个一个.mp3", tag="怪话"),
        VoiceFile(name="啊！", file_name="啊！.mp3", tag="惊吓"),
        VoiceFile(name="啊——昂", file_name="啊——昂.mp3", tag="惊吓"),
        VoiceFile(name="woc好高", file_name="woc好高.mp3", tag="惊吓"),
        VoiceFile(name="你别乱说啊啊！！", file_name="你别乱说啊啊.mp3", tag="惊吓"),
        VoiceFile(name="薯条不行", file_name="薯条不行.mp3", tag="跳脸"),
        VoiceFile(name="薯条8行~", file_name="薯条8行~.mp3", tag="跳脸"),
        VoiceFile(name="（lol）在你们面前放眼，哈哈", file_name="（lol）在你们面前放眼，哈哈.mp3", tag="跳脸"),
        VoiceFile(name="哈哈哈，vtb天狗", file_name="哈哈哈，vtb天狗.mp3", tag="跳脸"),
        VoiceFile(name="哈哈该你啦", file_name="哈哈该你啦.mp3", tag="跳脸"),
        VoiceFile(name="你们说不准吃我就要吃！", file_name="你们说不准吃我就要吃！.mp3", tag="跳脸"),
        VoiceFile(name="嘲讽薯条的流氓猫", file_name="嘲讽薯条的流氓猫.mp3", tag="跳脸"),
        VoiceFile(name="心情不好吃肉喵", file_name="心情不好吃肉喵.mp3", tag="跳脸"),
        VoiceFile(name="清晨~", file_name="清晨~.mp3", tag="跳脸")
    ]
)


__all__ = [
    'mnk_voices'
]
