from .model import VoiceFile, Voice


taffy_voices = Voice(
    resource_name='taffy_voice',
    voices=[
        VoiceFile(name="Bang……诶？", file_name="Bang……诶？-Bang...Uh？-怪叫-20220329_AAC.m4a", tag="怪叫"),
        VoiceFile(name="Bang……诶？", file_name="Bang……诶？-Bang...Uh？-怪叫-20220329_AAC_vocals_AAC.m4a", tag="怪叫"),
        VoiceFile(name="Bang咚咚咚咚咚", file_name="Bang咚咚咚咚咚-Bang dongdongdongdongdong-怪叫-20220329_AAC.m4a", tag="怪叫"),
        VoiceFile(name="Bang咚咚咚咚咚", file_name="Bang咚咚咚咚咚-Bang dongdongdongdongdong-怪叫-20220329_AAC_vocals_AAC.m4a", tag="怪叫"),
        VoiceFile(name="Bilibili好看", file_name="Bilibili好看-Bilibili is good-怪话-20220615_AAC.m4a", tag="怪话"),
        VoiceFile(name="B站唯一认证雏女", file_name="B站唯一认证雏女-The only certified virgin in Bilibili-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="Can can need bee", file_name="Can can need bee-Can can need bee-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="Can can need bee", file_name="Can can need bee-Can can need bee-怪话-20220414_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Cherry太多啦", file_name="Cherry太多啦-Too many cherry-怪话-20220419_AAC.m4a", tag="怪话"),
        VoiceFile(name="Cherry太多啦", file_name="Cherry太多啦-Too many cherry-怪话-20220419_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Cherry就是狗变的", file_name="Cherry就是狗变的-Cherry is a dog-攻击性-20220329_AAC.m4a", tag="攻击性"),
        VoiceFile(name="Cherry！", file_name="Cherry！-Cherry-可爱-20220419_AAC.m4a", tag="可爱"),
        VoiceFile(name="Cherry！", file_name="Cherry！-Cherry-可爱-20220419_vocals_AAC.m4a", tag="可爱"),
        VoiceFile(name="I Love Cherry 2", file_name="I Love Cherry 2-I Love Cherry 2-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="I Love Cherry", file_name="I Love Cherry-I Love Cherry-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="I Love Cherry", file_name="I Love Cherry-I Love Cherry-怪话-20220329_AAC_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Money Money Money", file_name="Money Money Money-Money Money Money-可爱-20220615_AAC.m4a", tag="可爱"),
        VoiceFile(name="Mua", file_name="Mua-Mua-可爱-20220419_AAC.m4a", tag="可爱"),
        VoiceFile(name="Nya", file_name="Nya-Nya-可爱-20220409_AAC.m4a", tag="可爱"),
        VoiceFile(name="Nya", file_name="Nya-Nya-可爱-20220615_vocals_AAC.m4a", tag="可爱"),
        VoiceFile(name="NyaNyaNya哼", file_name="NyaNyaNya哼-NyaNyaNya-怪叫-20220329_AAC.m4a", tag="怪叫"),
        VoiceFile(name="PvZ小调（也许是）", file_name="PvZ小调（也许是）-PvZ BGM-可爱-20220419_AAC.m4a", tag="可爱"),
        VoiceFile(name="Taffy 4000+了吗", file_name="Taffy 4000+了吗-Is Taffy 4000+-怪话-20220327_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy 4000+喽", file_name="Taffy 4000+喽-Taffy was 4000+-怪话-20220327_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy 4000了吗", file_name="Taffy 4000了吗-Is Taffy 4000-怪话-20220327_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy 4000喽", file_name="Taffy 4000喽-Taffy was 4000-怪话-20220327_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy一边舔雏草姬也能一边发出这个声音", file_name="Taffy一边舔雏草姬也能一边发出这个声音-Taffy can make this sound while licking Rotom-怪话-20220419_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy一边舔雏草姬也能一边发出这个声音", file_name="Taffy一边舔雏草姬也能一边发出这个声音-Taffy can make this sound while licking Rotom-怪话-20220419_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy也喜欢钓男人", file_name="Taffy也喜欢钓男人-Taffy also likes to fish for men-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy人见人爱，花见花开，独轮车见车爆胎", file_name="Taffy人见人爱，花见花开，独轮车见车爆胎-Taffy is loved by everyone-经典名言-20220615_vocals_AAC.m4a", tag="经典名言"),
        VoiceFile(name="Taffy会魔法了", file_name="Taffy会魔法了-Taffy learned magic-可爱-20220414_AAC.m4a", tag="可爱"),
        VoiceFile(name="Taffy口活好", file_name="Taffy口活好-Taffy has a good mouth-怪话-20220419_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy口活好", file_name="Taffy口活好-Taffy has a good mouth-怪话-20220419_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy告诉你没门", file_name="Taffy告诉你没门-.Taffy tells you no way-攻击性-20220401-vocals_AAC.m4a", tag="攻击性"),
        VoiceFile(name="Taffy告诉你没门", file_name="Taffy告诉你没门-.Taffy tells you no way-攻击性-20220401_AAC.m4a", tag="攻击性"),
        VoiceFile(name="Taffy喜欢两个头的", file_name="Taffy喜欢两个头的-Taffy likes dual head-怪话-20220419_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy喜欢两个头的", file_name="Taffy喜欢两个头的-Taffy likes dual head-怪话-20220419_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy喝口水", file_name="Taffy喝口水-Taffy wants to drink water-经典名言-20220414_AAC.m4a", tag="经典名言"),
        VoiceFile(name="Taffy大嫖客", file_name="Taffy大嫖客-Taffy is a big whore-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy就喜欢被人看所以开直播", file_name="Taffy就喜欢被人看所以开直播-Taffy likes to be watched so I started live streaming-怪话-20220416_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy尿太多了", file_name="Taffy尿太多了-Taffy urinates too much-尿频-20220416_AAC.m4a", tag="尿频"),
        VoiceFile(name="Taffy想帮雏草姬释放", file_name="Taffy想帮雏草姬释放-Taffy wants to help lotom free-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy我啊最喜欢叔叔了", file_name="Taffy我啊最喜欢叔叔了-Taffy like uncle the most-怪话-20220327_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy我啊最喜欢叔叔了", file_name="Taffy我啊最喜欢叔叔了-Taffy like uncle the most-怪话-20220327_AAC_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy把鸡烧了，变成了烧鸡", file_name="Taffy把鸡烧了，变成了烧鸡-Taffy burnt the chicken and turned it into a roast chicken-怪话-20220401_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy把鸡烧了，变成了烧鸡", file_name="Taffy把鸡烧了，变成了烧鸡-Taffy burnt the chicken and turned it into a roast chicken-怪话-20220401_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy搞热水器是为了温暖人心", file_name="Taffy搞热水器是为了温暖人心-Taffy does softcore to warm hearts-经典名言-20220416_AAC.m4a", tag="经典名言"),
        VoiceFile(name="Taffy是任务达人", file_name="Taffy是任务达人-Taffy is a mission master-怪话-20220416_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy是厂妹", file_name="Taffy是厂妹-Taffy is a factory girl-经典名言-20220401_AAC.m4a", tag="经典名言"),
        VoiceFile(name="Taffy是烧鸡", file_name="Taffy是烧鸡-Taffy is roast chicken-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy未开封喵", file_name="Taffy未开封喵-Taffy is unopened-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy没有毛", file_name="Taffy没有毛-Taffy has no hair-怪话-20220327_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy没有毛", file_name="Taffy没有毛-Taffy has no hair-怪话-20220327_AAC_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy滑了", file_name="Taffy滑了-Taffy cums-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy特别喜欢叫鸡", file_name="Taffy特别喜欢叫鸡-Taffy likes to eat chicken-怪话-20220615_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy的洞被僵尸啃了", file_name="Taffy的洞被僵尸啃了-Taffy's hole eaten by zombies-怪话-20210419_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy的洞被僵尸啃了", file_name="Taffy的洞被僵尸啃了-Taffy's hole eaten by zombies-怪话-20210419_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy的蛋要碎了", file_name="Taffy的蛋要碎了-Taffy's eggs are going to be broken-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy的蛋都烧着了", file_name="Taffy的蛋都烧着了-Taffy's eggs are on fire-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy的蛋都要裂了", file_name="Taffy的蛋都要裂了-Taffy's eggs are about to crack-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy被插了，怎么办呀被不停地插前面", file_name="Taffy被插了，怎么办呀被不停地插前面-Taffy gets plugged-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy要", file_name="Taffy要-Taffy wants-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy要吃甜甜的，白白的，奶油涂满的蛋糕", file_name="Taffy要吃甜甜的，白白的，奶油涂满的蛋糕-Taffy wants a sweet, white, creamy cake-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy要吃甜甜的，白白的，奶油涂满的蛋糕", file_name="Taffy要吃甜甜的，白白的，奶油涂满的蛋糕-Taffy wants a sweet, white, creamy cake-怪话-20220329_AAC_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy要吃饭", file_name="Taffy要吃饭-Taffy wants to eat-可爱-20220405_AAC.m4a", tag="可爱"),
        VoiceFile(name="Taffy要尿了", file_name="Taffy要尿了-Taffy is going to pee-尿频-20220401_AAC.m4a", tag="尿频"),
        VoiceFile(name="Taffy要把梁木都打了", file_name="Taffy要把梁木都打了-Taffy wants to untie all knobs-可爱-20220414_AAC.m4a", tag="可爱"),
        VoiceFile(name="Taffy要进去了", file_name="Taffy要进去了-Taffy is going in-怪话-20220113_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy要那个", file_name="Taffy要那个-Taffy wants to...-经典名言-20220405_AAC.m4a", tag="经典名言"),
        VoiceFile(name="Taffy要？", file_name="Taffy要？-Taffy wants to...-怪话-20220401_AAC.m4a", tag="怪话"),
        VoiceFile(name="Taffy要？", file_name="Taffy要？-Taffy wants to...-怪话-20220401_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="V", file_name="V-V-可爱-20220405_AAC.m4a", tag="可爱"),
        VoiceFile(name="【标准海鸥叫】", file_name="【标准海鸥叫】-Standard Sea Gull-海鸥-20220412_AAC.m4a", tag="海鸥"),
        VoiceFile(name="一把字支持住了永雏塔菲喵", file_name="一把字支持住了永雏塔菲喵-Support Taffy-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="一模一…", file_name="一模一…-They are the sam...-海鸥-20220308_AAC.m4a", tag="海鸥"),
        VoiceFile(name="上面的水下面的水都止不住地流", file_name="上面的水下面的水都止不住地流-The water above and the water below can't stop flowing-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="下半身断了", file_name="下半身断了-Broken lower body-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="不会", file_name="不会-Taffy doesn't know-哭泣-20220615_vocals_AAC.m4a", tag="哭泣"),
        VoiceFile(name="不会抓小偷", file_name="不会抓小偷-Taffy won't catch thieves-哭泣-20220615_vocals_AAC.m4a", tag="哭泣"),
        VoiceFile(name="不可以进到Taffy的洞里面去", file_name="不可以进到Taffy的洞里面去-Don't go into Taffy's portal-怪话-20220419_AAC.m4a", tag="怪话"),
        VoiceFile(name="不可以进到Taffy的洞里面去", file_name="不可以进到Taffy的洞里面去-Don't go into Taffy's portal-怪话-20220419_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="不可能！", file_name="不可能！-Impossible！-攻击性-20220401_AAC.m4a", tag="攻击性"),
        VoiceFile(name="不能在网上传播隐私图片喵", file_name="不能在网上传播隐私图片喵-You can't spread private pictures online-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="不要", file_name="不要-No-可爱-20220615_AAC.m4a", tag="可爱"),
        VoiceFile(name="不要再剧透了", file_name="不要再剧透了-No more spoilers-怪话-20220416_AAC.m4a", tag="怪话"),
        VoiceFile(name="不要再啃了", file_name="不要再啃了-Dont bite please-怪话-20220419_AAC.m4a", tag="怪话"),
        VoiceFile(name="不要再啃了", file_name="不要再啃了-Dont bite please-怪话-20220419_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="不要再射了", file_name="不要再射了-Dont shoot anymore-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="不要再射了", file_name="不要再射了-Dont shoot anymore-怪话-20220414_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="不要对着Taffy射", file_name="不要对着Taffy射-Don't cum to Taffy-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="不要对着Taffy射", file_name="不要对着Taffy射-Don't cum to Taffy-怪话-20220414_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="不要小孩开大车", file_name="不要小孩开大车-Don't let kids drive big cars-怪话-20220419_AAC.m4a", tag="怪话"),
        VoiceFile(name="不要小孩开大车", file_name="不要小孩开大车-Don't let kids drive big cars-怪话-20220419_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="不要蹭了快进去", file_name="不要蹭了快进去-Don't rub it, go in-怪话-20220113_AAC.m4a", tag="怪话"),
        VoiceFile(name="不要鲨鱼", file_name="不要鲨鱼-No Shark-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="买一只，买一只，买", file_name="买一只，买一只，买-Buy one, buy one, buy-经典名言-20220329_AAC.m4a", tag="经典名言"),
        VoiceFile(name="亚撒西的二次元Uncle", file_name="亚撒西的二次元Uncle-Gentle anime uncle-怪话-20220416_AAC.m4a", tag="怪话"),
        VoiceFile(name="亲嘴", file_name="亲嘴-Kiss-经典名言-20220401_AAC.m4a", tag="经典名言"),
        VoiceFile(name="什么b动静", file_name="什么b动静-What a fkin sound-经典名言-20220401_AAC.m4a", tag="经典名言"),
        VoiceFile(name="今天又是在逃公主的一天", file_name="今天又是在逃公主的一天-Today is another day for the princess on the run-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="他急了，哈哈", file_name="他急了，哈哈-He's in a hurry, haha-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="你们发射出来的弹幕滑过Taffy的脸", file_name="你们发射出来的弹幕滑过Taffy的脸-The danmaku you fired slid across Taffy's face-怪话-20220401_AAC.m4a", tag="怪话"),
        VoiceFile(name="你们发射出来的弹幕滑过Taffy的脸", file_name="你们发射出来的弹幕滑过Taffy的脸-The danmaku you fired slid across Taffy's face-怪话-20220401_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="你好流出来了", file_name="你好流出来了-Urine came out-尿频-20220329_AAC.m4a", tag="尿频"),
        VoiceFile(name="你的量太大了Taffy这边…灌不满", file_name="你的量太大了Taffy这边…灌不满-You gave too much-怪话-20220416_AAC.m4a", tag="怪话"),
        VoiceFile(name="停不下来的海鸥", file_name="停不下来的海鸥-Laugh-海鸥-20220308_AAC.m4a", tag="海鸥"),
        VoiceFile(name="全喷出来了", file_name="全喷出来了-It's all sprayed out-怪话-20220401_AAC.m4a", tag="怪话"),
        VoiceFile(name="全喷出来了", file_name="全喷出来了-It's all sprayed out-怪话-20220401_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="关注永雏塔菲喵，关注永雏塔菲谢谢喵", file_name="关注永雏塔菲喵，关注永雏塔菲谢谢喵-Follow Ace Taffy Nya-经典名言-20220329_AAC.m4a", tag="经典名言"),
        VoiceFile(name="关注永雏塔菲喵，关注永雏塔菲谢谢喵", file_name="关注永雏塔菲喵，关注永雏塔菲谢谢喵-Follow Ace Taffy Nya-经典名言-20220329_AAC_vocals_AAC.m4a", tag="经典名言"),
        VoiceFile(name="切割！", file_name="切割！-Cut！-经典名言-20220401_AAC.m4a", tag="经典名言"),
        VoiceFile(name="创似你", file_name="创似你-Hit you-攻击性-20220615_vocals_AAC.m4a", tag="攻击性"),
        VoiceFile(name="别动", file_name="别动-Dont move-经典名言-20220405_AAC.m4a", tag="经典名言"),
        VoiceFile(name="别在这发癫！", file_name="别在这发癫！-Frenzied Flame Seagull 2-海鸥-20220419_AAC.m4a", tag="海鸥"),
        VoiceFile(name="别在这发癫！", file_name="别在这发癫！-Frenzied Flame Seagull-海鸥-20220419_AAC.m4a", tag="海鸥"),
        VoiceFile(name="别急喵", file_name="别急喵-Don't worry-经典名言-20220327_AAC.m4a", tag="经典名言"),
        VoiceFile(name="发点能回的", file_name="发点能回的-Post something I can reply-经典名言-20220414_AAC.m4a", tag="经典名言"),
        VoiceFile(name="叫破喉咙也不会有人来救你的喵", file_name="叫破喉咙也不会有人来救你的喵-Nobody will come to save you-怪话-20220416_AAC.m4a", tag="怪话"),
        VoiceFile(name="可以尿尿吗，求求你了", file_name="可以尿尿吗，求求你了-Can i pee please-尿频-20220615_vocals_AAC.m4a", tag="尿频"),
        VoiceFile(name="吃奶！", file_name="吃奶！-Milk-怪话-20220416_AAC.m4a", tag="怪话"),
        VoiceFile(name="吸溜", file_name="吸溜-Suck-经典名言-20220419_AAC.m4a", tag="经典名言"),
        VoiceFile(name="吸溜", file_name="吸溜-Suck-经典名言-20220419_vocals_AAC.m4a", tag="经典名言"),
        VoiceFile(name="呜呜呜", file_name="呜呜呜-555-哭泣-20220329_AAC.m4a", tag="哭泣"),
        VoiceFile(name="呜呜呜2", file_name="呜呜呜2-555-哭泣-20220329_AAC.m4a", tag="哭泣"),
        VoiceFile(name="呜呜呜3", file_name="呜呜呜3-555 3-哭泣-20220329_AAC.m4a", tag="哭泣"),
        VoiceFile(name="呜呜呜太难了", file_name="呜呜呜太难了-555 It's too hard-哭泣-20220329_AAC.m4a", tag="哭泣"),
        VoiceFile(name="呻吟", file_name="呻吟-Moan-怪叫-20220405_AAC.m4a", tag="怪叫"),
        VoiceFile(name="呻吟", file_name="呻吟-Moan-怪叫-20220615_vocals_AAC.m4a", tag="怪叫"),
        VoiceFile(name="咚咚", file_name="咚咚-Heartbeat-可爱-20220409_AAC.m4a", tag="可爱"),
        VoiceFile(name="哈哈", file_name="哈哈-Haha-可爱-20220327_AAC.m4a", tag="可爱"),
        VoiceFile(name="哈哈", file_name="哈哈-Haha-可爱-20220401_AAC.m4a", tag="可爱"),
        VoiceFile(name="哈哈Cherry炸了", file_name="哈哈Cherry炸了-Haha cherry exploded-攻击性-20220419_AAC.m4a", tag="攻击性"),
        VoiceFile(name="哈哈Cherry炸了", file_name="哈哈Cherry炸了-Haha cherry exploded-攻击性-20220419_vocals_AAC.m4a", tag="攻击性"),
        VoiceFile(name="哈哈耶诶", file_name="哈哈耶诶-Haha Yeah-怪叫-20220401_AAC.m4a", tag="怪叫"),
        VoiceFile(name="哈哈耶诶", file_name="哈哈耶诶-Haha Yeah-怪叫-20220401_vocals_AAC.m4a", tag="怪叫"),
        VoiceFile(name="哈？", file_name="哈？-Ha？-攻击性-20220401_AAC.m4a", tag="攻击性"),
        VoiceFile(name="哒哒哒嘿嘿嘿", file_name="哒哒哒嘿嘿嘿-DadadaHeyheyhey-怪叫-20220329_AAC.m4a", tag="怪叫"),
        VoiceFile(name="哒哒哒嘿嘿嘿", file_name="哒哒哒嘿嘿嘿-DadadaHeyheyhey-怪叫-20220329_AAC_vocals_AAC.m4a", tag="怪叫"),
        VoiceFile(name="啊", file_name="啊-Scream-尖叫-20220401_AAC.m4a", tag="尖叫"),
        VoiceFile(name="啊↑啊↑啊↑", file_name="啊↑啊↑啊↑-Ah↑Ah↑Ah↑-怪叫-20220401_AAC.m4a", tag="怪叫"),
        VoiceFile(name="啊不要", file_name="啊不要-No-怪叫-20220419_AAC.m4a", tag="怪叫"),
        VoiceFile(name="啊不要", file_name="啊不要-No-怪叫-20220419_vocals_AAC.m4a", tag="怪叫"),
        VoiceFile(name="啊哈啊", file_name="啊哈啊-Ahh-怪叫-20220615_vocals_AAC.m4a", tag="怪叫"),
        VoiceFile(name="啊啊啊", file_name="啊啊啊-Scream-尖叫-20220329_AAC.m4a", tag="尖叫"),
        VoiceFile(name="啊啊啊啊啊", file_name="啊啊啊啊啊-AAAAA-尖叫-20220329_AAC.m4a", tag="尖叫"),
        VoiceFile(name="啊汪汪汪汪汪汪", file_name="啊汪汪汪汪汪汪-Bark-怪叫-20220401_AAC.m4a", tag="怪叫"),
        VoiceFile(name="啊，啊啊啊啊啊啊", file_name="啊，啊啊啊啊啊啊-A,AAAAA-尖叫-20220329_AAC.m4a", tag="尖叫"),
        VoiceFile(name="喵喵喵喵喵喵喵喵喵", file_name="喵喵喵喵喵喵喵喵喵-MeowMeowMeowMeowMeowMeowMeowMeowMeow-怪叫-20220414_AAC.m4a", tag="怪叫"),
        VoiceFile(name="嗨", file_name="嗨-Hi-可爱-20220329_AAC.m4a", tag="可爱"),
        VoiceFile(name="嗨", file_name="嗨-Hi-可爱-20220401_AAC.m4a", tag="可爱"),
        VoiceFile(name="嗨呀，是我吗", file_name="嗨呀，是我吗-Is it me-经典名言-20211230_AAC.m4a", tag="经典名言"),
        VoiceFile(name="嗯不要", file_name="嗯不要-Oh No-怪叫-20220329_AAC.m4a", tag="怪叫"),
        VoiceFile(name="嗯！", file_name="嗯！-Sodayo-经典名言-20220329_AAC.m4a", tag="经典名言"),
        VoiceFile(name="嗷呜嗷呜嗷呜", file_name="嗷呜嗷呜嗷呜-Aw Aw Aw-怪叫-20220329_AAC.m4a", tag="怪叫"),
        VoiceFile(name="嗷呜嗷呜嗷呜", file_name="嗷呜嗷呜嗷呜-Aw Aw Aw-怪叫-20220329_AAC_vocals_AAC.m4a", tag="怪叫"),
        VoiceFile(name="嘎嘎嘎嘎嘎", file_name="嘎嘎嘎嘎嘎-Quack-怪叫-20220401_AAC.m4a", tag="怪叫"),
        VoiceFile(name="嘻嘻", file_name="嘻嘻-Xixi-经典名言-20220414_AAC.m4a", tag="经典名言"),
        VoiceFile(name="嘻嘻嘻", file_name="嘻嘻嘻-Xixixi-怪叫-20220401_AAC.m4a", tag="怪叫"),
        VoiceFile(name="嘿嘿", file_name="嘿嘿-Heihei-可爱-20220329_AAC.m4a", tag="可爱"),
        VoiceFile(name="塔菲汁没有，堵住了", file_name="塔菲汁没有，堵住了-No taffy juice, it was blocked-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="大无语事件", file_name="大无语事件-Something speechless-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="太大了不要", file_name="太大了不要-Too big, no-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="失足少女", file_name="失足少女-Lost girl-海鸥-20220302_AAC.m4a", tag="海鸥"),
        VoiceFile(name="女人好可怕", file_name="女人好可怕-Woman is scary-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="奸笑", file_name="奸笑-Sinister smile-怪叫-20220329_AAC.m4a", tag="怪叫"),
        VoiceFile(name="好似", file_name="好似-Nice Death-经典名言-20211212_AAC.m4a", tag="经典名言"),
        VoiceFile(name="好似喵 好似喵 好似喵", file_name="好似喵 好似喵 好似喵-Nice Death-经典名言-20220414_AAC.m4a", tag="经典名言"),
        VoiceFile(name="好似喵", file_name="好似喵-Open champagne-经典名言-20220327_AAC.m4a", tag="经典名言"),
        VoiceFile(name="好似海鸥", file_name="好似海鸥-Nice Death Seagull-海鸥-20211212_AAC.m4a", tag="海鸥"),
        VoiceFile(name="好似过啦哈哈", file_name="好似过啦哈哈-Nice death passed the review-经典名言-20211212_AAC.m4a", tag="经典名言"),
        VoiceFile(name="好大的棒子", file_name="好大的棒子-Such a huge stick-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="好大的？头", file_name="好大的？头-such a large excalibur-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="好大的？头", file_name="好大的？头-such a large excalibur-怪话-20220329_AAC_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="好想来", file_name="好想来-I really want to come-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="好玩儿 欸嘿", file_name="好玩儿 欸嘿-Funny-经典名言-20220419_AAC.m4a", tag="经典名言"),
        VoiceFile(name="妈妈Taffy要喝奶", file_name="妈妈Taffy要喝奶-Mom Taffy wants milk-怪话-20220416_AAC.m4a", tag="怪话"),
        VoiceFile(name="妈妈你好烧呀", file_name="妈妈你好烧呀-Mom Youre so hot-怪话-20220416_AAC.m4a", tag="怪话"),
        VoiceFile(name="妈妈这是什么呀", file_name="妈妈这是什么呀-Mama whats this-可爱-20220414_AAC.m4a", tag="可爱"),
        VoiceFile(name="委屈的哼声", file_name="委屈的哼声-Wronged-可爱-20220401_AAC.m4a", tag="可爱"),
        VoiceFile(name="它就想射Taffy身上", file_name="它就想射Taffy身上-It wants to cum on Taffy-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="它就想射Taffy身上", file_name="它就想射Taffy身上-It wants to cum on Taffy-怪话-20220414_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="它的肚子比奈子还大", file_name="它的肚子比奈子还大-Its belly is bigger than chest-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="宅宅们发福利咯", file_name="宅宅们发福利咯-Homeboys, I'll give benefits-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="完了Taffy的洞要被进去了怎么回事呀", file_name="完了Taffy的洞要被进去了怎么回事呀-Taffy's hole is about to be entered, what's going on-怪话-20220419_AAC.m4a", tag="怪话"),
        VoiceFile(name="完了Taffy的洞要被进去了怎么回事呀", file_name="完了Taffy的洞要被进去了怎么回事呀-Taffy's hole is about to be entered, what's going on-怪话-20220419_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="完整的海鸥打鸣", file_name="完整的海鸥打鸣-Full Sea Gull sound-海鸥-20220413_AAC.m4a", tag="海鸥"),
        VoiceFile(name="完整的海鸥打鸣", file_name="完整的海鸥打鸣-Full Sea Gull sound-海鸥-20220413_vocals_AAC.m4a", tag="海鸥"),
        VoiceFile(name="射多一点还能射到Taffy的脸上", file_name="射多一点还能射到Taffy的脸上-Cum a little more and get to Taffy's face-怪话-20220401_AAC.m4a", tag="怪话"),
        VoiceFile(name="射多一点还能射到Taffy的脸上", file_name="射多一点还能射到Taffy的脸上-Cum a little more and get to Taffy's face-怪话-20220401_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="小丑", file_name="小丑-Joker-经典名言-20220414_AAC.m4a", tag="经典名言"),
        VoiceFile(name="小菲小菲 最爱犟嘴 小菲小菲 打倒小菲", file_name="小菲小菲 最爱犟嘴 小菲小菲 打倒小菲-Support slogan-经典名言-20220327_AAC.m4a", tag="经典名言"),
        VoiceFile(name="小雏草姬哪里都小", file_name="小雏草姬哪里都小-Little Rotom is small everywhere-攻击性-20220419_AAC.m4a", tag="攻击性"),
        VoiceFile(name="小雏草姬哪里都小", file_name="小雏草姬哪里都小-Little Rotom is small everywhere-攻击性-20220419_vocals_AAC.m4a", tag="攻击性"),
        VoiceFile(name="小雏草姬大麻烦", file_name="小雏草姬大麻烦-little rotom big trouble-怪话-20220419_AAC.m4a", tag="怪话"),
        VoiceFile(name="小雏草姬大麻烦", file_name="小雏草姬大麻烦-little rotom big trouble-怪话-20220419_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="少女失足中", file_name="少女失足中-Losting-怪叫-20220302_AAC.m4a", tag="怪叫"),
        VoiceFile(name="尿尿咯", file_name="尿尿咯-It's time to pee-尿频-20220615_AAC.m4a", tag="尿频"),
        VoiceFile(name="尿尿喽", file_name="尿尿喽-Pee time-尿频-20220329_AAC.m4a", tag="尿频"),
        VoiceFile(name="尿尿时间到", file_name="尿尿时间到-It's time to pee-尿频-20220401_AAC.m4a", tag="尿频"),
        VoiceFile(name="干什么呀", file_name="干什么呀-What are you doing-可爱-20220401_AAC.m4a", tag="可爱"),
        VoiceFile(name="开什么玩笑要吐了", file_name="开什么玩笑要吐了-What a joke I'm going to throw up-经典名言-20220329_AAC.m4a", tag="经典名言"),
        VoiceFile(name="开可乐咯", file_name="开可乐咯-Open champagne-经典名言-20211212_AAC.m4a", tag="经典名言"),
        VoiceFile(name="快来看bee", file_name="快来看bee-Come to look at bee-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="快来看bee", file_name="快来看bee-Come to look at bee-怪话-20220414_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="快点Taffy要进去", file_name="快点Taffy要进去-Come on, Taffy is going in-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="怎么回事呀", file_name="怎么回事呀-What's going on-经典名言-20220419_AAC.m4a", tag="经典名言"),
        VoiceFile(name="怎么回事呀", file_name="怎么回事呀-What's going on-经典名言-20220419_vocals_AAC.m4a", tag="经典名言"),
        VoiceFile(name="怎么回事呀", file_name="怎么回事呀-Whats the matter-经典名言-20220414_AAC.m4a", tag="经典名言"),
        VoiceFile(name="怪笑", file_name="怪笑-Strange Laugh-海鸥-20220401_AAC.m4a", tag="海鸥"),
        VoiceFile(name="惊声尖叫", file_name="惊声尖叫-Scream 2-尖叫-20220401_AAC.m4a", tag="尖叫"),
        VoiceFile(name="惊声尖叫", file_name="惊声尖叫-Scream-尖叫-20220401_AAC.m4a", tag="尖叫"),
        VoiceFile(name="想导就导", file_name="想导就导-Do what you want to do-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="想跟Taffy超来超去", file_name="想跟Taffy超来超去-Wants to overtake Taffy-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="愤怒 愤怒 愤怒", file_name="愤怒 愤怒 愤怒-Angry Angry Angry-经典名言-20220414_AAC.m4a", tag="经典名言"),
        VoiceFile(name="愤怒愤怒", file_name="愤怒愤怒-Angry Angry-经典名言-20220326_AAC.m4a", tag="经典名言"),
        VoiceFile(name="愤怒愤怒愤怒", file_name="愤怒愤怒愤怒-Angry-经典名言-20220615_vocals_AAC.m4a", tag="经典名言"),
        VoiceFile(name="憋不住", file_name="憋不住-Laugh 1-海鸥-20220308_AAC.m4a", tag="海鸥"),
        VoiceFile(name="憋不住", file_name="憋不住-Laugh-海鸥-20220308_AAC.m4a", tag="海鸥"),
        VoiceFile(name="憋着会坏掉的", file_name="憋着会坏掉的-It will break if you hold it-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="我真的会谢", file_name="我真的会谢-I will really thank you-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="打起来 打起来 打似一个算一个", file_name="打起来 打起来 打似一个算一个-fight, fight, kill one count as one-攻击性-20220615_vocals_AAC.m4a", tag="攻击性"),
        VoiceFile(name="把麦克风打掉喵", file_name="把麦克风打掉喵-Drop your microphone-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="拜拜喵 拜拜喵 Nya", file_name="拜拜喵 拜拜喵 Nya-Byebye Nya-经典名言-20220414_AAC.m4a", tag="经典名言"),
        VoiceFile(name="拜拜喵", file_name="拜拜喵-Goodbye Nya-经典名言-20220327_AAC.m4a", tag="经典名言"),
        VoiceFile(name="数一数二的烧鸡", file_name="数一数二的烧鸡-Nice Fried Chicken-经典名言-20211230_AAC.m4a", tag="经典名言"),
        VoiceFile(name="无能狂怒", file_name="无能狂怒-Impotent Fury-怪叫-20220329_AAC.m4a", tag="怪叫"),
        VoiceFile(name="暴风吸入，好喝到翘脚脚", file_name="暴风吸入，好喝到翘脚脚-Drink like crazy-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="有梁木", file_name="有梁木-There is wood-可爱-20220414_AAC.m4a", tag="可爱"),
        VoiceFile(name="根本停不下来", file_name="根本停不下来-Can not stop at all-可爱-20220615_vocals_AAC.m4a", tag="可爱"),
        VoiceFile(name="榨汁喽", file_name="榨汁喽-Juicing Time-怪话-20220405_AAC.m4a", tag="怪话"),
        VoiceFile(name="欸嘿嘿嘿嘿", file_name="欸嘿嘿嘿嘿-Xixixi-可爱-20220401_AAC.m4a", tag="可爱"),
        VoiceFile(name="比铁还硬，比钢还强的是Taffy的嘴", file_name="比铁还硬，比钢还强的是Taffy的嘴-Harder than iron, stronger than steel is Taffy's mouth-经典名言-20220615_vocals_AAC.m4a", tag="经典名言"),
        VoiceFile(name="气急败坏", file_name="气急败坏-Out of breath-怪叫-20220329_AAC.m4a", tag="怪叫"),
        VoiceFile(name="汉堡", file_name="汉堡-Hamburger-可爱-20220414_AAC.m4a", tag="可爱"),
        VoiceFile(name="汪汪汪", file_name="汪汪汪-Bark-怪叫-20220329_AAC.m4a", tag="怪叫"),
        VoiceFile(name="没有！", file_name="没有！-No!-经典名言-20220401_AAC.m4a", tag="经典名言"),
        VoiceFile(name="没有！", file_name="没有！-No!-经典名言-20220401_vocals_AAC.m4a", tag="经典名言"),
        VoiceFile(name="没有！", file_name="没有！-No-经典名言-20220419_AAC.m4a", tag="经典名言"),
        VoiceFile(name="没有！", file_name="没有！-No-经典名言-20220419_vocals_AAC.m4a", tag="经典名言"),
        VoiceFile(name="注入得太多了", file_name="注入得太多了-Inject too much-怪话-20220401_AAC.m4a", tag="怪话"),
        VoiceFile(name="注入得太多了", file_name="注入得太多了-Inject too much-怪话-20220401_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="海鸥大笑", file_name="海鸥大笑-Huge Laugh-海鸥-20220308_AAC.m4a", tag="海鸥"),
        VoiceFile(name="滑了", file_name="滑了-Cum-怪话-20211230_AAC.m4a", tag="怪话"),
        VoiceFile(name="烧鸡", file_name="烧鸡-Roast chicken-怪话-20220401_AAC.m4a", tag="怪话"),
        VoiceFile(name="烧鸡", file_name="烧鸡-Roast chicken-怪话-20220401_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="爆金币喽", file_name="爆金币喽-Received the money-怪话-20220405_AAC.m4a", tag="怪话"),
        VoiceFile(name="爽诶", file_name="爽诶-Feels good-可爱-20220414_AAC.m4a", tag="可爱"),
        VoiceFile(name="牛奶", file_name="牛奶-Milk-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="牛牛", file_name="牛牛-Cattle-可爱-20220401_AAC.m4a", tag="可爱"),
        VoiceFile(name="猫头呢", file_name="猫头呢-Where is the cat head-可爱-20220414_AAC.m4a", tag="可爱"),
        VoiceFile(name="玩儿~玩儿~玩儿~", file_name="玩儿~玩儿~玩儿~-Play, play, play-怪叫-20220329_AAC.m4a", tag="怪叫"),
        VoiceFile(name="生理反应", file_name="生理反应-physiological response-怪话-20220615_AAC.m4a", tag="怪话"),
        VoiceFile(name="男人都喜欢盯着Taffy看", file_name="男人都喜欢盯着Taffy看-Men like to stare at Taffy-怪话-20220409_AAC.m4a", tag="怪话"),
        VoiceFile(name="留条命随便玩儿", file_name="留条命随便玩儿-Spare my life plz-经典名言-20220416_AAC.m4a", tag="经典名言"),
        VoiceFile(name="疯狂的独轮车", file_name="疯狂的独轮车-Crazy unicycle-经典名言-20220615_vocals_AAC.m4a", tag="经典名言"),
        VoiceFile(name="看到Taffy这么可爱的美女给他手冲牛奶咖啡他肯定非常的兴奋", file_name="看到Taffy这么可爱的美女给他手冲牛奶咖啡他肯定非常的兴奋-He must be very excited to see such a lovely beauty as Taffy making him coffee with milk-怪话-20220409_AAC.m4a", tag="可爱"),
        VoiceFile(name="看看你的", file_name="看看你的-Look yours-怪话-20220327_AAC.m4a", tag="怪话"),
        VoiceFile(name="真是无语住了", file_name="真是无语住了-I'm speechless-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="真是绝绝子", file_name="真是绝绝子-Absolutely-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="突发恶疾", file_name="突发恶疾-Sudden Laugh-海鸥-20220308_AAC.m4a", tag="海鸥"),
        VoiceFile(name="突然呻吟", file_name="突然呻吟-Sudden moan-怪叫-20220414_AAC.m4a", tag="怪叫"),
        VoiceFile(name="给它的洞按住它就出不了水了", file_name="给它的洞按住它就出不了水了-Hold it down on its hole and it won't get out of the water-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="给永雏塔菲Money喵，给永雏塔菲Money谢谢喵", file_name="给永雏塔菲Money喵，给永雏塔菲Money谢谢喵-Give Taffy Money Please-经典名言-20220615_AAC.m4a", tag="经典名言"),
        VoiceFile(name="绷不住", file_name="绷不住-Cannot hold on to laugh-海鸥-20220308_AAC.m4a", tag="海鸥"),
        VoiceFile(name="绷不住", file_name="绷不住-Laugh-海鸥-20220308_AAC.m4a", tag="海鸥"),
        VoiceFile(name="绷不住的海鸥", file_name="绷不住的海鸥-Laugh-海鸥-20220308_AAC.m4a", tag="海鸥"),
        VoiceFile(name="老公", file_name="老公-Husband-经典名言-20220401_AAC.m4a", tag="经典名言"),
        VoiceFile(name="老公复刻", file_name="老公复刻-Darling-经典名言-20220419_AAC.m4a", tag="经典名言"),
        VoiceFile(name="耶诶", file_name="耶诶-Yeah-经典名言-20220327_AAC.m4a", tag="经典名言"),
        VoiceFile(name="耶诶", file_name="耶诶-Yeah-经典名言-20220401_AAC.m4a", tag="经典名言"),
        VoiceFile(name="耶诶", file_name="耶诶-Yeah~-经典名言-20220401_AAC.m4a", tag="经典名言"),
        VoiceFile(name="耶诶喵", file_name="耶诶喵-Yeah Meow-经典名言-20220414_AAC.m4a", tag="经典名言"),
        VoiceFile(name="耶诶！", file_name="耶诶！-Yeah！-经典名言-20220401_AAC.m4a", tag="经典名言"),
        VoiceFile(name="胡萝卜", file_name="胡萝卜-Carrot-可爱-20220329_AAC.m4a", tag="可爱"),
        VoiceFile(name="脑壳都疼了", file_name="脑壳都疼了-My Brain hurts-可爱-20220615_vocals_AAC.m4a", tag="可爱"),
        VoiceFile(name="腿给你打断", file_name="腿给你打断-Brake your legs-攻击性-20220615_vocals_AAC.m4a", tag="攻击性"),
        VoiceFile(name="自我 本我 超我", file_name="自我 本我 超我-ego id superego-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="臭似你们，不洗澡", file_name="臭似你们，不洗澡-I stink, I don't take a bath-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="花30元SC拨打Taffy热线", file_name="花30元SC拨打Taffy热线-Send 30R Superchat to call Taffy-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="草", file_name="草-Grass-可爱-20220419_AAC.m4a", tag="可爱"),
        VoiceFile(name="草", file_name="草-Grass-可爱-20220419_vocals_AAC.m4a", tag="可爱"),
        VoiceFile(name="蒸汽机漏气", file_name="蒸汽机漏气-Water heater leak-海鸥-20220412_AAC.m4a", tag="海鸥"),
        VoiceFile(name="薯条", file_name="薯条-Fries-可爱-20220401_AAC.m4a", tag="可爱"),
        VoiceFile(name="让Taffy进去好不好", file_name="让Taffy进去好不好-Let Taffy in please-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="让世界充满温暖", file_name="让世界充满温暖-Make the world warm-可爱-20220416_AAC.m4a", tag="可爱"),
        VoiceFile(name="诶哈哈哈哈哈哈", file_name="诶哈哈哈哈哈哈-Eh Hahaha-怪叫-20220414_AAC.m4a", tag="怪叫"),
        VoiceFile(name="谁要看bee", file_name="谁要看bee-Who wants to visit bee-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="软软的，白白的", file_name="软软的，白白的-Soft and white-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="这就是活在当下", file_name="这就是活在当下-This is what we call living in the moment-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="这是扭蛋机吧", file_name="这是扭蛋机吧-Is it a jerk machine-怪话-20220329_AAC.m4a", tag="怪话"),
        VoiceFile(name="这游戏太吓人了，太难了", file_name="这游戏太吓人了，太难了-This game is so scary, so hard-哭泣-20220401_AAC.m4a", tag="哭泣"),
        VoiceFile(name="这牛牛怎么会顶人", file_name="这牛牛怎么会顶人-How can this cow beat people-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="连续尖叫", file_name="连续尖叫-Continuous Screaming-尖叫-20220401_AAC.m4a", tag="尖叫"),
        VoiceFile(name="连续怪叫", file_name="连续怪叫-Continuous screams-怪叫-20220401_AAC.m4a", tag="怪叫"),
        VoiceFile(name="连续海鸥", file_name="连续海鸥-Continuous Laugh-海鸥-20220308_AAC.m4a", tag="海鸥"),
        VoiceFile(name="遛狗，艾特永雏塔菲", file_name="遛狗，艾特永雏塔菲-Waking dog, AceTaffy-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="释放自我", file_name="释放自我-Free yourself-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="重玩儿", file_name="重玩儿-Replay-经典名言-20220401_AAC.m4a", tag="经典名言"),
        VoiceFile(name="重玩儿", file_name="重玩儿-Replay-经典名言-20220401_vocals_AAC.m4a", tag="经典名言"),
        VoiceFile(name="金坷垃我们都要它", file_name="金坷垃我们都要它-We all want Jinkela-怪话-20220416_AAC.m4a", tag="怪话"),
        VoiceFile(name="钢门僵尸被吸了", file_name="钢门僵尸被吸了-Screen Door Zombie was sucked-怪话-20220419_AAC.m4a", tag="怪话"),
        VoiceFile(name="钢门僵尸被吸了", file_name="钢门僵尸被吸了-Screen Door Zombie was sucked-怪话-20220419_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="铸币海鸥", file_name="铸币海鸥-Piggy Seagull-海鸥-20211230_AAC.m4a", tag="海鸥"),
        VoiceFile(name="锵锵", file_name="锵锵-Clang-可爱-20220329_AAC.m4a", tag="可爱"),
        VoiceFile(name="锵锵锵锵锵锵", file_name="锵锵锵锵锵锵-Clang Clang-可爱-20220329_AAC.m4a", tag="可爱"),
        VoiceFile(name="集美们发大水了", file_name="集美们发大水了-Sisters orgasm-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="集美们我真的栓Q", file_name="集美们我真的栓Q-I really thank you guys-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="雏草姬5秒一只", file_name="雏草姬5秒一只-Rotom can only last five seconds-怪话-20220416_AAC.m4a", tag="怪话"),
        VoiceFile(name="雏草姬不要啦", file_name="雏草姬不要啦-Lotom No-怪话-20220405_AAC.m4a", tag="怪话"),
        VoiceFile(name="雏草姬别动", file_name="雏草姬别动-Lotom Dont move-怪话-20220419_AAC.m4a", tag="怪话"),
        VoiceFile(name="雏草姬别拿雏草姬的头蹭Taffy喵", file_name="雏草姬别拿雏草姬的头蹭Taffy喵-don't rub Taffy with Rotom‘s head-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="雏草姬发臭了", file_name="雏草姬发臭了-Lotom stinks-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="雏草姬就爱回旋，雏草姬就是陀螺", file_name="雏草姬就爱回旋，雏草姬就是陀螺-Rotom likes to spin, Rotom is a top-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="雏草姬有好多梁木", file_name="雏草姬有好多梁木-Lotom has many knobs-可爱-20220414_AAC.m4a", tag="可爱"),
        VoiceFile(name="雏草姬的蛋只会送给别人，雏草姬没用", file_name="雏草姬的蛋只会送给别人，雏草姬没用-Rotom's eggs are only given to others, Rotom is useless-怪话-20220615_vocals_AAC.m4a", tag="怪话"),
        VoiceFile(name="雏草姬门都没有", file_name="雏草姬门都没有-Lotom no way-攻击性-20220615_vocals_AAC.m4a", tag="攻击性"),
        VoiceFile(name="雏草姬骗人", file_name="雏草姬骗人-Rotom is lying-哭泣-20220329_AAC.m4a", tag="哭泣"),
        VoiceFile(name="雏草姬骗人", file_name="雏草姬骗人-Rotom is lying-哭泣-20220329_AAC_vocals_AAC.m4a", tag="哭泣"),
        VoiceFile(name="非常愉快Desu", file_name="非常愉快Desu-Very Pleasant desu-可爱-20220416_AAC.m4a", tag="可爱"),
        VoiceFile(name="非常抱歉，你要找的界面不见了", file_name="非常抱歉，你要找的界面不见了-404-怪话-20220615_AAC.m4a", tag="怪话"),
        VoiceFile(name="骗人", file_name="骗人-Youre lying-经典名言-20220414_AAC.m4a", tag="经典名言"),
        VoiceFile(name="骗子4001", file_name="骗子4001-Lier 4001-经典名言-20220401_AAC.m4a", tag="经典名言"),
        VoiceFile(name="鬼笑", file_name="鬼笑-Ghost Laugh-怪叫-20220401_AAC.m4a", tag="怪叫"),
        VoiceFile(name="鱼为什么在钓鱼啊", file_name="鱼为什么在钓鱼啊-Why are the fish fishing-怪话-20220414_AAC.m4a", tag="怪话"),
        VoiceFile(name="黑厂", file_name="黑厂-Black factory-可爱-20220327_AAC.m4a", tag="可爱"),
        VoiceFile(name="？头很硬", file_name="？头很硬-Head is hard-怪话-20220329_AAC_vocals_AAC.m4a", tag="怪话"),
    ]
)


__all__ = [
    'taffy_voices'
]
